root: true
plugins:
  - react
  - '@typescript-eslint'
extends:
  - react-app
  - react-app/jest
  - prettier
parser: '@typescript-eslint/parser'
env: {}
rules:
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/explicit-function-return-type': off
